Updated README
aardito2143/Onlinebookstore-group-4 pull request #21
Opened 2023-03-20 18:47 UTC by Dbevan770

2023-03-20 18:54 UTC, TaylorLee23 approved these changes
Great job! Working on presentation.

2023-03-20 18:55 UTC, TaeLynne requested changes
Adam is the Scrum Master and I am the Product Owner

Everything else looks good!

2023-03-21 14:28 UTC, aardito2143 approved these changes

2023-03-21 14:32 UTC, TaeLynne approved these changes

2023-03-21 14:32 UTC, merged